language: ruby
rvm:
  - 2.3.0
  - 2.5.0

gemfile:
  - gemfiles/activemodel4.gemfile
  - gemfiles/activemodel5.gemfile
  - gemfiles/activemodel6.gemfile

matrix:
  exclude:
    - rvm: 2.3.0
      gemfile: gemfiles/activemodel6.gemfile
    - rvm: 2.5.0
      gemfile: gemfiles/activemodel4.gemfile

before_install: gem install bundler
